import { PancakeSwapTokens } from './tokens'

export const ifo = [
  {
    id: 'ARENA',
    chain: 'BSC',
    isActive: true,
    isVested: true,
    poolContract: '0xC7d259712a26fa33a9a94cFB58964a67dAB27095',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/arena-bg.png',
    startBlock: 24835300,
    endBlock: 24837700,
    privatePool: {
      saleAmount: 8750000,
      raiseAmount: 350000,
    },
    publicPool: {
      saleAmount: 26250000,
      raiseAmount: 1050000,
    },
    isCIFO: false,
    requiredPoints: 0,
    unlockPercent: 33,
    tokenOfferingPrice: 0.04,
    tokenDetails: {
      name: PancakeSwapTokens.arena.name,
      symbol: PancakeSwapTokens.arena.symbol,
      address: PancakeSwapTokens.arena.contractAddress,
      decimal: PancakeSwapTokens.arena.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xCfFD4D3B517b77BE32C76DA768634dE6C738889B.png',
      website: 'https://espl.co/',
      telegram: 'esplarena',
      twitter: 'ESPL_GLOBAL',
      description:
        'From the team: “ARENA is a multi-chain utility token that allows token holders to enjoy premium offerings on the ESPL Arena platform. Token holders can launch their own tournaments with ARENA prize pool and gain exclusive access to limited edition NFT blind boxes. ARENA can also be used as advertising expenses by guilds, game publishers and brand advertisers.',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.cake.symbol,
    quoteTokenAddress: PancakeSwapTokens.cake.contractAddress,
    syrupPoolAddress: '',
  },
  {
    id: 'SQUAD',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0x57EB2e676863435A140F8Bc2a0F0e955C36ED446',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/squad-bg.png',
    startBlock: 23924870,
    endBlock: 23927270,
    privatePool: {
      saleAmount: 10000000,
      raiseAmount: 350000,
    },
    publicPool: {
      saleAmount: 15000000,
      raiseAmount: 525000,
    },
    isCIFO: true,
    requiredPoints: 90,
    unlockPercent: 20,
    tokenOfferingPrice: 0.035,
    tokenDetails: {
      name: PancakeSwapTokens.squad.name,
      symbol: PancakeSwapTokens.squad.symbol,
      address: PancakeSwapTokens.squad.contractAddress,
      decimal: PancakeSwapTokens.squad.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x724A32dFFF9769A0a0e1F0515c0012d1fB14c3bd.png',
      website: 'https://ssquad.games/',
      telegram: 'Superpower_Squad',
      twitter: 'Superpow_Squad',
      description: 'Superpower Squad a super-hero themed mobile shooter with 6 game play modes. It has undergone 3 years of game development from an established gaming studio with the help of crypto native partners.',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.cake.symbol,
    quoteTokenAddress: PancakeSwapTokens.cake.contractAddress,
    syrupPoolAddress: '',
  },
  {
    id: 'MGP',
    chain: 'BSC',
    isActive: true,
    isVested: true,
    poolContract: '0x3FE5A79d4264fe65A1a9E3938286428a0E2e214D',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/mgp-bg.png',
    startBlock: 22539050,
    endBlock: 22540250,
    privatePool: {
      saleAmount: 17500000,
      raiseAmount: 437500,
    },
    publicPool: {
      saleAmount: 52500000,
      raiseAmount: 1312500,
    },
    isCIFO: false,
    requiredPoints: 0,
    unlockPercent: 30,
    tokenOfferingPrice: 0.025,
    tokenDetails: {
      name: PancakeSwapTokens.mgp.name,
      symbol: PancakeSwapTokens.mgp.symbol,
      address: PancakeSwapTokens.mgp.contractAddress,
      decimal: PancakeSwapTokens.mgp.decimals,
      totalSupply: '100,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xD06716E1Ff2E492Cc5034c2E81805562dd3b45fa.png',
      website: 'https://www.magpiexyz.io/',
      telegram: 'magpiexyz_official',
      twitter: 'magpiexyz_io',
      description: 'Magpie is a customized fork of Convex that helps users in the Wombat ecosystem to obtain better yields and voting power',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.busd.symbol,
    quoteTokenAddress: PancakeSwapTokens.busd.contractAddress,
    syrupPoolAddress: '0x365F744c8b7608253697cA2Ed561537B65a3438B',
  },
  {
    id: 'WMX',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0xC202eb5f2487DA3675c4aAa2C3D2c071078699c1',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/wmx-bg.png',
    startBlock: 22282010,
    endBlock: 22284410,
    privatePool: {
      saleAmount: 1000000,
      raiseAmount: 3000000,
    },
    publicPool: {
      saleAmount: 3000000,
      raiseAmount: 9000000,
    },
    isCIFO: false,
    requiredPoints: 0,
    unlockPercent: 20,
    tokenOfferingPrice: 0.3,
    tokenDetails: {
      name: PancakeSwapTokens.wmx.name,
      symbol: PancakeSwapTokens.wmx.symbol,
      address: PancakeSwapTokens.wmx.contractAddress,
      decimal: PancakeSwapTokens.wmx.decimals,
      totalSupply: '100,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xa75d9ca2a0a1D547409D82e1B06618EC284A2CeD.png',
      website: 'https://wombex.finance/',
      telegram: 'wombex',
      twitter: 'WombexFinance',
      description: 'Wombex is a customized fork of Convex, designed specifically for the Wombat Exchange ecosystem',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.busd.symbol,
    quoteTokenAddress: PancakeSwapTokens.busd.contractAddress,
    syrupPoolAddress: '0xaEd58Af2c98dbF05d26B3E5b3cc809fc70D203ce',
  },
  {
    id: 'KRS',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0x4CCB9960dEF2f9a55D1a0454a134a8Adb0047B8e',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/krs-bg.png',
    startBlock: 22110940,
    endBlock: 22113340,
    privatePool: {
      saleAmount: 12000000,
      raiseAmount: 420000,
    },
    publicPool: {
      saleAmount: 18000000,
      raiseAmount: 630000,
    },
    isCIFO: true,
    requiredPoints: 800,
    unlockPercent: 20,
    tokenOfferingPrice: 0.035,
    tokenDetails: {
      name: PancakeSwapTokens.krs.name,
      symbol: PancakeSwapTokens.krs.symbol,
      address: PancakeSwapTokens.krs.contractAddress,
      decimal: PancakeSwapTokens.krs.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x37b53894e7429f794B56F22a32E1695567Ee9913.png',
      website: 'https://kingdomraids.io/',
      telegram: 'kingdomraidschat',
      twitter: 'KingdomRaids',
      description:
        'Kingdom Raids is a blockhain-based strategy Role-playing game (RPG) with a NFT metaverse. the game takes palce in fictional kingdom, "Dood kingdom", a land of mystery of adventure with over 40 heores in the mystic world, each possessing unique abilities.',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.busd.symbol,
    quoteTokenAddress: PancakeSwapTokens.busd.contractAddress,
    syrupPoolAddress: null,
  },
  {
    id: 'co',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0x8baEEE7d68cB332C63B3E4A8740072121070A2df',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/co-bg.png',
    startBlock: 21724430,
    endBlock: 21726830,
    privatePool: {
      saleAmount: 10500000,
      raiseAmount: 367500,
    },
    publicPool: {
      saleAmount: 31500000,
      raiseAmount: 1102500,
    },
    isCIFO: false,
    requiredPoints: 0,
    unlockPercent: 30,
    tokenOfferingPrice: 0.035,
    tokenDetails: {
      name: PancakeSwapTokens.co.name,
      symbol: PancakeSwapTokens.co.symbol,
      address: PancakeSwapTokens.co.contractAddress,
      decimal: PancakeSwapTokens.co.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x936B6659Ad0C1b244Ba8Efe639092acae30dc8d6.png',
      website: 'https://corite.com',
      telegram: 'corite',
      twitter: 'Coritecom',
      description: 'Corite is a blockchain-based music platform jointly powered by fans and artists to finance and promote music in a unique Engage-to-Earn (E2E) model.',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.busd.symbol,
    quoteTokenAddress: PancakeSwapTokens.busd.contractAddress,
    syrupPoolAddress: '0x31736A52bBdda4eaf0117B17736306Bbecb711ca',
  },
  {
    id: 'KRS',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0x8baEEE7d68cB332C63B3E4A8740072121070A2df',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/co-bg.png',
    startBlock: 21724430,
    endBlock: 21726830,
    privatePool: {
      saleAmount: 12000000,
      raiseAmount: 420000,
    },
    publicPool: {
      saleAmount: 18000000,
      raiseAmount: 630000,
    },
    isCIFO: true,
    requiredPoints: 800,
    unlockPercent: 20,
    tokenOfferingPrice: 0.035,
    tokenDetails: {
      name: PancakeSwapTokens.co.name,
      symbol: PancakeSwapTokens.co.symbol,
      address: PancakeSwapTokens.co.contractAddress,
      decimal: PancakeSwapTokens.co.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x936B6659Ad0C1b244Ba8Efe639092acae30dc8d6.png',
      website: 'https://kingdomraids.io/',
      telegram: 'kingdomraidschat',
      twitter: 'KingdomRaids',
      description:
        'Kingdom Raids is a blockhain-based strategy Role-playing game (RPG) with a NFT metaverse. the game takes palce in fictional kingdom, "Dood kingdom", a land of mystery of adventure with over 40 heores in the mystic world, each possessing unique abilities.',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.busd.symbol,
    quoteTokenAddress: PancakeSwapTokens.busd.contractAddress,
    syrupPoolAddress: '0x31736A52bBdda4eaf0117B17736306Bbecb711ca',
  },
  {
    id: 'hoop',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0x326e9E1B685C7F366fb320e7eC59599F3d88b1a2',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/hoop-bg.png',
    startBlock: 21524650,
    endBlock: 21527050,
    privatePool: {
      saleAmount: 6499500,
      raiseAmount: 357472.5,
    },
    publicPool: {
      saleAmount: 15165500,
      raiseAmount: 834102.5,
    },
    isCIFO: true,
    requiredPoints: 800,
    unlockPercent: 25,
    tokenOfferingPrice: 0.055,
    tokenDetails: {
      name: PancakeSwapTokens.hoop.name,
      symbol: PancakeSwapTokens.hoop.symbol,
      address: PancakeSwapTokens.hoop.contractAddress,
      decimal: 18,
      totalSupply: '350,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xF19cfb40B3774dF6Eed83169Ad5aB0Aaf6865F25.png',
      website: 'https://www.chibidinos.io/',
      telegram: 'chibidinos',
      twitter: 'DinosChibi',
      description: 'Chibi Dinos is a basketball and dinosaur themed metaverse with games such as Primal Hoop, an arcade basketball game with an adventure role-playing game (RPG) mode and Primal Pickem, a predictive play-to earn game (P2E).',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.busd.symbol,
    quoteTokenAddress: PancakeSwapTokens.busd.contractAddress,
    syrupPoolAddress: '0x6C254E3AB3e4B909A2CfAA3E0b9d2B3F7887CFae',
  },
  {
    id: 'wom',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0x98828e9D69E49104a62ecb4FA3d6F9e06A295CBA',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/wom-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 2800000,
      raiseAmount: 210000,
    },
    publicPool: {
      saleAmount: 25200000,
      raiseAmount: 1890000,
    },
    unlockPercent: 20,
    tokenOfferingPrice: 0.075,
    tokenDetails: {
      name: PancakeSwapTokens.wom.name,
      symbol: PancakeSwapTokens.wom.symbol,
      address: PancakeSwapTokens.wom.contractAddress,
      decimal: PancakeSwapTokens.wom.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1.png',
      website: 'https://wombat.exchange',
      telegram: 'WombatExchange',
      twitter: 'WombatExchange',
      description:
        'Wombat Exchange is a next generation multi-chain stableswap native to BNB Chain. Utilizing a stableswap 2.0 model, Wombat users are able to: swap stablecoins at hyper-efficient exchange rates with minimal slippage and earn a sustainable and optimal yield on their assets via single-staking pools.',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.busd.symbol,
    quoteTokenAddress: PancakeSwapTokens.busd.contractAddress,
    syrupPoolAddress: '0xf78DB5b635bA108212C9D84c124a52D7B1596b97',
  },
  {
    id: 'peel',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0x35Bb6Dd4E8C63491057c32621c8cDdE43BabE201',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/peel-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 10000000,
      raiseAmount: 400000,
    },
    publicPool: {
      saleAmount: 40000000,
      raiseAmount: 1600000,
    },
    unlockPercent: 20,
    tokenOfferingPrice: 0.04,
    tokenDetails: {
      name: PancakeSwapTokens.peel.name,
      symbol: PancakeSwapTokens.peel.symbol,
      address: PancakeSwapTokens.peel.contractAddress,
      decimal: PancakeSwapTokens.peel.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x734548a9e43d2D564600b1B2ed5bE9C2b911c6aB.png',
      website: 'https://metaapesgame.com/',
      telegram: '',
      twitter: 'MetaApesGame',
      description: 'Meta Apes is a free-to-play, play-and-earn massively multiplayer online (MMO) strategy game designed for mobile and the first game to launch on the BNB Sidechain with their own dedicated chain, Ape Chain.',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.busd.symbol,
    quoteTokenAddress: PancakeSwapTokens.busd.contractAddress,
  },
  {
    id: 'trivia',
    chain: 'BSC',
    isActive: false,
    isVested: true,
    poolContract: '0x23C520d8227524E2cDD00360358864fF3fFC36b4',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/trivia-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 10000000,
      raiseAmount: 350000,
    },
    publicPool: {
      saleAmount: 40000000,
      raiseAmount: 1400000,
    },
    tokenOfferingPrice: 0.035,
    tokenDetails: {
      name: PancakeSwapTokens.trivia.name,
      symbol: PancakeSwapTokens.trivia.symbol,
      address: PancakeSwapTokens.trivia.contractAddress,
      decimal: PancakeSwapTokens.trivia.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xb465f3cb6Aba6eE375E12918387DE1eaC2301B05.png',
      website: 'https://trivians.io/',
      telegram: 'TriviansGlobal',
      twitter: 'PlayTrivians',
      description:
        'Trivian is a trivia gaming platform with different game modes such as multiplayer mode, single player mode, 1v1 games, instant play, scheduled tournaments, and live shows … all while earning TRIVIA tokens! There are over 100,000 questions archived and updated on a daily basi',
    },
    gasLimits: {
      approve: 50000,
      deposit: 350000,
      harvest: 350000,
      swap: 400000,
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'duet',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0xDF24BE326af4c1fb888f567f41D9a981A4752cf1',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/duet-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 1200000,
      raiseAmount: 360000,
    },
    publicPool: {
      saleAmount: 48000000,
      raiseAmount: 1440000,
    },
    tokenOfferingPrice: 0.03,
    tokenDetails: {
      name: PancakeSwapTokens.duet.name,
      symbol: PancakeSwapTokens.duet.symbol,
      address: PancakeSwapTokens.duet.contractAddress,
      decimal: PancakeSwapTokens.duet.decimals,
      totalSupply: '420,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x95EE03e1e2C5c4877f9A298F1C0D6c98698FAB7B.png',
      website: 'https://duet.finance',
      telegram: 'duetprotocol',
      twitter: 'duetprotocol',
      description: 'DUET Protocol is a multi-chain synthetic assets ecosystem, enabling pegged assets from various markets – from individual stocks, to indexes, ETFs, and commodities.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'era',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0x527201a43f8da24ce9b7c21744a0706942f41fa3',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/era-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 4000000,
      raiseAmount: 360000,
    },
    publicPool: {
      saleAmount: 16000000,
      raiseAmount: 1440000,
    },
    tokenOfferingPrice: 0.09,
    tokenDetails: {
      name: PancakeSwapTokens.era.name,
      symbol: PancakeSwapTokens.era.symbol,
      address: PancakeSwapTokens.era.contractAddress,
      decimal: PancakeSwapTokens.era.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x6f9F0c4ad9Af7EbD61Ac5A1D4e0F2227F7B0E5f9.png',
      website: 'https://www.era7.io',
      telegram: 'Era7_Official',
      twitter: 'Era7_official',
      description: 'Drawing from their experience in traditional games such as Awakening of Dragon, Era7: Game of Truth combines elements of DeFi, NFTs, and Trading Cards into a play-to-earn game steeped in mythology and magic.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'froyo',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0xE0d6c91860a332068bdB59275b0AAC8769e26Ac4',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/froyo-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 20000000,
      raiseAmount: 1200000,
    },
    publicPool: {
      saleAmount: 46666668,
      raiseAmount: 2800000,
    },
    tokenOfferingPrice: 0.06,
    tokenDetails: {
      name: PancakeSwapTokens.froyo.name,
      symbol: PancakeSwapTokens.froyo.symbol,
      address: PancakeSwapTokens.froyo.contractAddress,
      decimal: PancakeSwapTokens.froyo.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xe369fec23380f9F14ffD07a1DC4b7c1a9fdD81c9.png',
      website: 'https://froyo.games',
      telegram: 'froyogames',
      twitter: 'realfroyogames',
      description: 'Froyo Games is a game publisher and decentralized GameFi platform, with a NFT Marketplace that integrates NFTs with their games.\n \n FROYO tokens can be used to buy NFTs and participate in Froyo games',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'dpt',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0x63914805A0864e9557eA3A5cC86cc1BA054ec64b',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/dpt-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 7200000,
      raiseAmount: 180000,
    },
    publicPool: {
      saleAmount: 16800000,
      raiseAmount: 420000,
    },
    tokenOfferingPrice: 0.025,
    tokenDetails: {
      name: PancakeSwapTokens.dpt.name,
      symbol: PancakeSwapTokens.dpt.symbol,
      address: PancakeSwapTokens.dpt.contractAddress,
      decimal: PancakeSwapTokens.dpt.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xE69cAef10A488D7AF31Da46c89154d025546e990.png',
      website: 'https://diviner.finance',
      telegram: 'DivinerProtocolOfficial',
      twitter: 'DivinerProtocol',
      description: 'Diviner Protocol aims to build up a metaverse “Diviner Harbor City” to offer users a lossless & gamified prediction marketplace by combining the best of DeFi and NFTs.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'santos',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0x69B5D2Ab0cf532a0E22Fc0dEB0c5135639892468',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/santos-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 120000,
      raiseAmount: 300000,
    },
    publicPool: {
      saleAmount: 280000,
      raiseAmount: 700000,
    },
    tokenOfferingPrice: 2.5,
    tokenDetails: {
      name: PancakeSwapTokens.santos.name,
      symbol: PancakeSwapTokens.santos.symbol,
      address: PancakeSwapTokens.santos.contractAddress,
      decimal: PancakeSwapTokens.santos.decimals,
      totalSupply: '1,000,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xA64455a4553C9034236734FadDAddbb64aCE4Cc7.png',
      website: 'https://twitter.com/SantosFC',
      telegram: 'SantosFC',
      twitter: 'SantosFC',
      description:
        'The Santos FC Fan Token is a BEP-20 utility token designed to revolutionize the fan experience for all Santos FC supporters. The token empowers Santos FC fans to participate in team voting polls, hunt digital collectibles, purchase NFTs, and enjoy gamification features that are tied to fan rewards or great experiences.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'porto',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0xFDFf29dD0b4DD49Bf5E991A30b8593eaA34B4580',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/porto-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 250000,
      raiseAmount: 500000,
    },
    publicPool: {
      saleAmount: 250000,
      raiseAmount: 500000,
    },
    tokenOfferingPrice: 2,
    tokenDetails: {
      name: PancakeSwapTokens.porto.name,
      symbol: PancakeSwapTokens.porto.symbol,
      address: PancakeSwapTokens.porto.contractAddress,
      decimal: PancakeSwapTokens.porto.decimals,
      totalSupply: '40,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x49f2145d6366099e13B10FbF80646C0F377eE7f6.png',
      website: 'https://twitter.com/FCPorto',
      telegram: 'FCPorto',
      twitter: 'FCPorto',
      description:
        'The FC Porto Fan Token is a BEP-20 utility token designed to revolutionize the fan experience for all FC Porto supporters. The token empowers FC Porto fans to participate in team voting polls, hunt digital collectibles, purchase NFTs, and enjoy gamification features that are tied with fan rewards or great experiences.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'dar',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0xb6eF1f36220397c434A6B15dc5EA616CFFDF58CE',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/dar-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 6000000,
      raiseAmount: 450000,
    },
    publicPool: {
      saleAmount: 6000000,
      raiseAmount: 450000,
    },
    tokenOfferingPrice: 0.075,
    tokenDetails: {
      name: PancakeSwapTokens.dar.name,
      symbol: PancakeSwapTokens.dar.symbol,
      address: PancakeSwapTokens.dar.contractAddress,
      decimal: PancakeSwapTokens.dar.decimals,
      totalSupply: '800,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x23CE9e926048273eF83be0A3A8Ba9Cb6D45cd978.png',
      website: 'https://www.minesofdalarnia.com/',
      telegram: 'MinesOfDalarnia',
      twitter: 'MinesOfDalarnia',
      description:
        'Mines of Dalarnia is a play-to-earn action-adventure game with procedurally generated levels on BSC. Players mine and collect various in-game items (i.e. minerals, rare relics and artifacts), improve their skills and gear to unlock the secrets of the Dalarnia universe. There are different mines with varying terrains to be explored and monsters to conquer in the quest for rare resources of the Dalarnian world.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'dkt',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0x89ab9852155A794e371095d863aEAa2DF198067C',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/dkt-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 75000,
      raiseAmount: 131250,
    },
    publicPool: {
      saleAmount: 175000,
      raiseAmount: 306250,
    },
    tokenOfferingPrice: 1.75,
    tokenDetails: {
      name: PancakeSwapTokens.dkt.name,
      symbol: PancakeSwapTokens.dkt.symbol,
      address: PancakeSwapTokens.dkt.contractAddress,
      decimal: PancakeSwapTokens.dkt.decimals,
      totalSupply: '10,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x7Ceb519718A80Dd78a8545AD8e7f401dE4f2faA7.png',
      website: 'https://duelistking.com/',
      telegram: 'DuelistKingNFT',
      twitter: 'duelistkingnft',
      description:
        'Powered by an in-house Decentralized Autonomous Organization (DAO), Oracle and Random Number Generator, Duelist King is the first generational NFT card game that aims to transform the way people play, participate and earn in card games through top-notch game play, asset designs and advocacy for the sustainable future of Win2Earn.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'kalmar',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0x1aFB32b76696CdF05593Ca3f3957AEFB23a220FB',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/kalmar-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 375000,
      raiseAmount: 750000,
    },
    publicPool: {
      saleAmount: 875000,
      raiseAmount: 2500000,
    },
    tokenOfferingPrice: 2.0,
    tokenDetails: {
      name: PancakeSwapTokens.kalm.name,
      symbol: PancakeSwapTokens.kalm.symbol,
      address: PancakeSwapTokens.kalm.contractAddress,
      decimal: PancakeSwapTokens.kalm.decimals,
      totalSupply: '10,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x4BA0057f784858a48fe351445C672FF2a3d43515.png',
      website: 'https://kalmar.io/',
      telegram: 'kalmar_io',
      twitter: 'kalmar_io',
      description: 'Kalmar is a decentralized bank powered by DeFi and NFT. Kalmar’s mission is combining the best of decentralized finance protocols and fueling them with pure fun!',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'hotcross',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0xb664cdbe385656F8c54031c0CB12Cea55b584b63',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/hotcross-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 375000,
      raiseAmount: 750000,
    },
    publicPool: {
      saleAmount: 875000,
      raiseAmount: 2500000,
    },
    tokenOfferingPrice: 2.0,
    tokenDetails: {
      name: PancakeSwapTokens.hotcross.name,
      symbol: PancakeSwapTokens.hotcross.symbol,
      address: PancakeSwapTokens.hotcross.contractAddress,
      decimal: PancakeSwapTokens.hotcross.decimals,
      totalSupply: '500,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0x4FA7163E153419E0E1064e418dd7A99314Ed27b6.png',
      website: 'https://www.hotcross.com/',
      telegram: 'HotCross',
      twitter: 'hotcrosscom',
      description: 'Hot Cross is a multi-chain tool suite that enables blockchain teams and their communities to thrive.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
  {
    id: 'horizon',
    chain: 'BSC',
    isActive: false,
    isVested: false,
    poolContract: '0x6137B571f7F1E44839ae10310a08be86D1A4D03B',
    ifoBanner: 'https://pancakeswap.finance/images/ifos/horizon-bg.png',
    startBlock: 20893660,
    endBlock: 20896060,
    privatePool: {
      saleAmount: 3000000,
      raiseAmount: 750000,
    },
    publicPool: {
      saleAmount: 7000000,
      raiseAmount: 1750000,
    },
    tokenOfferingPrice: 0.25,
    tokenDetails: {
      name: PancakeSwapTokens.hzn.name,
      symbol: PancakeSwapTokens.hzn.symbol,
      address: PancakeSwapTokens.hzn.contractAddress,
      decimal: PancakeSwapTokens.hzn.decimals,
      totalSupply: '100,000,000',
      tokenLogo: 'https://pancakeswap.finance/images/tokens/0xC0eFf7749b125444953ef89682201Fb8c6A917CD.png',
      website: 'https://horizonprotocol.com/',
      telegram: 'HorizonProtocol',
      twitter: 'HorizonProtocol',
      description:
        'Horizon Protocol is a new DeFi platform that facilitates the on-chain trading of synthetic assets that represent the real economy. Horizon Protocol seeks to provide exposure to real-world assets risk/return profiles via smart contracts on the blockchain.',
    },
    quoteToken: PancakeSwapTokens.wbnb.symbol,
    quoteTokenAddress: PancakeSwapTokens.wbnb.contractAddress,
  },
]
