import ETHLogo from 'assets/images/Blockchains/Ethereum.svg'
import BNBLogo from 'assets/images/Blockchains/Binance.svg'
import AvaxLogo from 'assets/images/Blockchains/Avalanche.svg'
import FantomLogo from 'assets/images/Blockchains/Fantom.svg'
import MaticLogo from 'assets/images/Blockchains/Matic.svg'
import ArbitrumLogo from 'assets/images/Blockchains/Arbitrum.svg'
import OptimisticLogo from 'assets/images/Blockchains/Optimistic.svg'
import HarmonyLogo from 'assets/images/Blockchains/Harmony.svg'
import OKBLogo from 'assets/images/Blockchains/OKB.svg'
import CronosLogo from 'assets/images/Blockchains/Cronos.svg'
import HuobiLogo from 'assets/images/Blockchains/Huobi.svg'
import VelasLogo from 'assets/images/Blockchains/Velas.svg'

import {
  BNBChain,
  AvalancheChain,
  FantomChain,
  OKEXChain,
  PolygonChain,
  HecoChain,
  HarmonyChain,
  ArbitrumChain,
  OptimisticETHChain,
  VelasChain,
  CronosChain,
  BSCTestnetChain,
  PolygonMumbaiChain,
  ShardeumLiberty1Chain,
  ShardeumLiberty2Chain,
  ShardeumSphinx1
} from 'utils/EVMNetworks'

import Button from 'components/Button'

export const networks = {
  mainnet: [
    {
      id: 'BSC',
      type: 'Mainnet',
      name: 'Smart Chain',
      logo: BNBLogo,
      rpc: 'https://bsc-dataseed.binance.org/',
      chainId: 56,
      symbol: 'BNB',
      explorer: 'https://bscscan.com/',
      action: <Button onClick={() => BNBChain()}>დამატება</Button>,
    },
    {
      id: 'AVAX',
      type: 'Mainnet',
      name: 'Avalanche C-Chain',
      logo: AvaxLogo,
      rpc: 'https://avalanche-mainnet.infura.io',
      chainId: 43114,
      symbol: 'AVAX',
      explorer: 'https://snowtrace.io/',
      action: <Button onClick={() => AvalancheChain()}>დამატება</Button>,
    },
    {
      id: 'FANTOM',
      type: 'Mainnet',
      name: 'Fantom',
      logo: FantomLogo,
      rpc: 'https://www.ankr.com/rpc/fantom/',
      chainId: 250,
      symbol: 'FTM',
      explorer: 'https://ftmscan.com/',
      action: <Button onClick={() => FantomChain()}>დამატება</Button>,
    },
    {
      id: 'MATIC',
      type: 'Mainnet',
      name: 'Polygon',
      logo: MaticLogo,
      rpc: 'https://polygon-mainnet.infura.io',
      chainId: 137,
      symbol: 'MATIC',
      explorer: 'https://polygonscan.com/',
      action: <Button onClick={() => PolygonChain()}>დამატება</Button>,
    },
    {
      id: 'CRONOS',
      type: 'Mainnet',
      name: 'Cronos',
      logo: CronosLogo,
      rpc: 'https://evm.cronos.org/',
      chainId: 25,
      symbol: 'CRO',
      explorer: 'https://cronoscan.com',
      action: <Button onClick={() => CronosChain()}>დამატება</Button>,
    },
    {
      id: 'ARBITRUM',
      type: 'Mainnet',
      name: 'Arbitrum',
      logo: ArbitrumLogo,
      rpc: 'https://arbitrum-mainnet.infura.io',
      chainId: 42161,
      symbol: 'ETH',
      explorer: 'https://arbiscan.io/',
      action: <Button onClick={() => ArbitrumChain()}>დამატება</Button>,
    },
    {
      id: 'OPTIMISM',
      type: 'Mainnet',
      name: 'Optimism',
      logo: OptimisticLogo,
      rpc: 'hhttps://optimism-mainnet.infura.io',
      chainId: 10,
      symbol: 'ETH',
      explorer: 'https://optimistic.etherscan.io/',
      action: <Button onClick={() => OptimisticETHChain()}>დამატება</Button>,
    },
    {
      id: 'Harmony',
      type: 'Mainnet',
      name: 'Harmony',
      logo: HarmonyLogo,
      rpc: 'https://api.harmony.one',
      chainId: 1666600000,
      symbol: 'ONE',
      explorer: 'https://explorer.harmony.one/',
      action: <Button onClick={() => HarmonyChain()}>დამატება</Button>,
    },
    {
      id: 'OKX',
      type: 'Mainnet',
      name: 'OKX',
      logo: OKBLogo,
      rpc: 'https://exchainrpc.okex.org',
      chainId: 66,
      symbol: 'OKT',
      explorer: 'https://www.oklink.com/okc',
      action: <Button onClick={() => OKEXChain()}>დამატება</Button>,
    },
    {
      id: 'Heco',
      type: 'Mainnet',
      name: 'HECO',
      logo: HuobiLogo,
      rpc: 'https://http-mainnet.hecochain.com',
      chainId: 128,
      symbol: 'HT',
      explorer: 'https://hecoinfo.com/',
      action: <Button onClick={() => HecoChain()}>დამატება</Button>,
    },
    {
      id: 'Velas',
      type: 'Mainnet',
      name: 'Velas',
      logo: VelasLogo,
      rpc: 'https://evmexplorer.velas.com/rpc',
      chainId: 106,
      symbol: 'VLX',
      explorer: 'https://evmexplorer.velas.com',
      action: <Button onClick={() => VelasChain()}>დამატება</Button>,
    },
  ],
  testnet: [
    {
      id: 'bsc_testnet',
      type: 'Testnet',
      name: 'BSC',
      logo: BNBLogo,
      rpc: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
      chainId: 97,
      symbol: 'tBNB',
      explorer: 'https://testnet.bscscan.com',
      action: <Button onClick={() => BSCTestnetChain()}>დამატება</Button>,
    },
    {
      id: 'matic_testnet',
      type: 'Testnet',
      name: 'Polygon - Mumbai',
      logo: MaticLogo,
      rpc: 'https://matic-mumbai.chainstacklabs.com',
      chainId: 80001,
      symbol: 'MATIC',
      explorer: 'https://mumbai.polygonscan.com/',
      action: <Button onClick={() => PolygonMumbaiChain()}>დამატება</Button>,
    },
    {
      id: 'shardeum1_testnet',
      type: 'Testnet',
      name: 'Shardeum Liberty 1.5',
      logo: ETHLogo,
      rpc: 'https://liberty10.shardeum.org/',
      chainId: 8080,
      symbol: 'SHM',
      explorer: 'https://explorer-liberty10.shardeum.org',
      action: <Button onClick={() => ShardeumLiberty1Chain()}>დამატება</Button>,
    },
    {
      id: 'shardeum2_testnet',
      type: 'Testnet',
      name: 'Shardeum Liberty 2.0',
      logo: ETHLogo,
      rpc: 'https://liberty20.shardeum.org/',
      chainId: 8081,
      symbol: 'SHM',
      explorer: 'https://explorer-liberty20.shardeum.org',
      action: <Button onClick={() => ShardeumLiberty2Chain()}>დამატება</Button>,
    },
    {
      id: 'shardeumshpinx_testnet',
      type: 'Testnet',
      name: 'Shardeum Sphinx 1.X',
      logo: ETHLogo,
      rpc: 'https://sphinx.shardeum.org/',
      chainId: 8082,
      symbol: 'SHM',
      explorer: 'https://explorer-sphinx.shardeum.org/',
      action: <Button onClick={() => ShardeumSphinx1()}>დამატება</Button>,
    },
  ],
}
